apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-deployment-dev
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  project: prod
  source:
    path: .
    repoURL: "https://github.com/pjlewisuk/project-deployment-dev"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true