apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: {{ .Values.destination.gitopsNamespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.destination.namespace }}
    server: {{ .Values.destination.server }}
  project: {{ .Values.project }}
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.4.2
    helm:
      values: |
        controller:
          service:
            annotations:
              "service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path"=/healthz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true