apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeapps
  namespace: {{ .Values.destination.gitopsNamespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.destination.namespace }}
    server: {{ .Values.destination.server }}
  project: {{ .Values.project }}
  source:
    chart: kubeapps
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.2.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true